name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the action daily at midnight UTC.
  workflow_dispatch:  # Allows manual triggering of the workflow.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add Upstream
        run: git remote add upstream https://github.com/jy0205/Pyramid-Flow.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Merge Upstream Changes
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push Changes
        run: |
          git push origin main
